### ISSUE TITLE
TypeError: nil can't be coerced into Integer when scraping resource metrics for non-ready pod

### ISSUE THREAD

**Issue by jpatokal** [splunk/fluent-plugin-k8s-metrics-agg#31]
**What happened**:

The following error on startup:

```
2019-08-09 02:42:40 +0000 [info]: #0 Use URL https://10.96.0.1/api/v1/nodes/user-cluster1-58cd54f877-wmlzw:10250/proxy/stats/summary for scraping resource usage metrics
2019-08-09 02:42:40 +0000 [error]: #0 Failed to scrape metrics, error=, #<TypeError: nil can't be coerced into Integer>
2019-08-09 02:42:40 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-k8s-metrics-agg-1.1.0/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:104:in `+'
2019-08-09 02:42:40 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-k8s-metrics-agg-1.1.0/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:104:in `add_resource_usage_metrics'
2019-08-09 02:42:40 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-k8s-metrics-agg-1.1.0/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb:573:in `block (3 levels) in process_resource_usage_res'
```

Tracing up the stack, it looks like [the code is hardcoded](https://github.com/splunk/fluent-plugin-k8s-metrics-agg/blob/develop/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb#L569) to expect fields `usageNanoCores, usageBytes, namespace` to *always* be present for each pod and can't handle it if they are not, eg. if the pod is still starting up.

**What you expected to happen**:

Missing value would be ignored or retried.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure how to repro actual event, but simulating this by feeding in some JSON with a field missing should be pretty trivial.

**Anything else we need to know?**:

**Environment**:
```
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5
b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:
"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.19", GitCommit:"a23b6496cc1fdc6bbb888f
cb09374c70a848a0f5", GitTreeState:"clean", BuildDate:"2019-05-10T04:06:49Z", GoVersion:"go1.10.8b4", Compiler:"gc",
 Platform:"linux/amd64"}
```

- Splunk version:
fluent-plugin-k8s-metrics-agg-1.1.0

**Comment by chaitanyaphalak** [comment]
Thanks @jpatokal for reporting the issue. I would be happy to review a PR for the same.

**Comment by gswallow** [comment]
I think we're hitting this bug, too.  Would this work?

`           pod_cpu_usage = pod_json['cpu'].fetch('usageNanoCores', 0)/ 1_000_000
              pod_memory_usage = pod_json['memory'].fetch('usageBytes', 0)
`

If so, I can submit a PR.

**Comment by rockb1017** [comment]
Thank you. I have updated the code accordingly and release 1.1.4.
